name: Static Code Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checks:
    env:
      src: "hpoflow tests docs setup.py"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[checking]

    - name: Check with black
      run: black ${{ env.src }} --check --diff

    - name: Check with flake8
      run: flake8 ${{ env.src }}

    - name: Check with isort
      run: isort ${{ env.src }} --check --diff

    - name: Check with mdformat
      run: mdformat --check *.md

    - name: Check with style-doc
      run: style-doc --max_len 99 --check_only ${{ env.src }}
